import streamlit as st
import json
import os
import networkx as nx
from pyvis.network import Network
import streamlit.components.v1 as components

# --- 1. Page setup and default file path ---
st.set_page_config(layout="wide")
st.title("🛡️ Apache Log4j Attack Graph Visualization")

# Path to the JSON file generated by Team 2
GRAPH_JSON_FILE = "attack_graph.json"

# --- 2. Check whether the file exists ---
if not os.path.exists(GRAPH_JSON_FILE):
    st.error(f"Cannot find file '{GRAPH_JSON_FILE}'.")
    st.warning(
        "Before running this script, "
        f"make sure the `{GRAPH_JSON_FILE}` file is in the **same folder** as this script."
    )
    st.stop() # Stop the app if the file doesn't exist

# --- 3. Load data ---
st.subheader("1. Data Loading")
try:
    with open(GRAPH_JSON_FILE, 'r', encoding='utf-8') as f:
        graph_data = json.load(f)

    nodes_count = len(graph_data.get('nodes', []))
    links_count = len(graph_data.get('links', []))

    st.info(f"✅ Successfully loaded '{GRAPH_JSON_FILE}'! (Nodes: {nodes_count}, Links: {links_count})")

except Exception as e:
    st.error(f"Error loading '{GRAPH_JSON_FILE}': {e}")
    st.stop()


# --- 4. Create NetworkX graph ---
try:
    node_link_data = {
        "nodes": graph_data.get('nodes', []),
        "links": graph_data.get('links', [])
    }

    G = nx.node_link_graph(node_link_data, directed=True, multigraph=False)
    st.success("NetworkX graph object created successfully.")

except Exception as e:
    st.error(f"Error creating NetworkX graph: {e}")
    st.stop()


# --- 5. Interactive graph visualization using Pyvis ---
st.subheader("2. Interactive Graph (Pyvis)")

# [Fix 1] Change background to white (#ffffff), default font to black
net = Network(height="750px", width="100%", bgcolor="#ffffff", font_color="black", notebook=False, directed=True)

# 1. Add nodes (same as before)
node_data_map = {}
for node in graph_data.get('nodes', []):
    # 1. Check whether the node is a dict
    if isinstance(node, dict):
        # Prefer 'cve_id'; fall back to 'id', then 'name'
        cve_id = node.get('cve_id') or node.get('id') or node.get('name')

        if cve_id:
            node_data_map[cve_id] = node
        else:
            # Warning message when no ID can be found (for debugging)
            st.warning(f"⚠️ Warning: Skipping a node with no identifier (ID): {node}")

    # 2. If the node is a string ("CVE-XXX") instead of a dict
    elif isinstance(node, str):
        node_data_map[node] = {"cve_id": node}

for n in G.nodes():
    cve_id = n
    data = node_data_map.get(cve_id)

    title = f"<b>ID:</b> {cve_id}" # default tooltip
    color = "#6E9BFF" # default color (blue tone)
    shape = "ellipse" # default ellipse shape

    if data:
        # Use plain text and newlines (\n) instead of HTML tags (<b>, <br>)
        title = (
            f"ID: {cve_id}\n"
            f"Type: {data.get('vulnerability_type', 'N/A')}\n"
            f"Description: {data.get('description', 'N/A')}\n"
        )

    try:
        value = G.degree(cve_id) * 5 + 10 # larger for nodes with more connections
    except:
        value = 10

    # Highlight the CVE-2021-44228 node
    if cve_id == "CVE-2021-44228":
        color = "#FF4136" # red
        value = 50

    net.add_node(
        n,
        label=cve_id,
        title=title,
        shape=shape,
        color=color,
        value=value
    )

# 2. Add edges (links)
for u, v, data in G.edges(data=True):
    edge_title = data.get("description", "N/A")
    net.add_edge(u, v, label="", title=edge_title, arrows="to")


# Physics simulation and style options
net.toggle_physics(True)

# [Fix 2] Change font and arrow colors in options_json
options_json = """
{
  "nodes": {
    "font": {
      "color": "#000000",
      "size": 14
    },
    "borderWidth": 2
  },
  "edges": {
    "font": {
      "color": "#000000",
      "size": 14,
      "align": "middle",
      "strokeWidth": 0
    },
    "color": {
      "color": "#2B7CE9",
      "highlight": "#0055FF",
      "hover": "#0055FF"
    },
    "arrows": {
      "to": { "enabled": true, "scaleFactor": 0.5 }
    },
    "smooth": {
      "type": "continuous"
    }
  },
  "physics": {
    "barnesHut": {
      "gravitationalConstant": -1000,
      "centralGravity": 0.1,
      "springLength": 100,
      "springConstant": 0.05
    },
    "minVelocity": 0.75,
    "solver": "barnesHut"
  }
}
"""
# nodes.font.color: "#000000" (changed to black so it's visible on the white background)
# edges.color.color: "#2B7CE9" (changed the arrow color to blue)

net.set_options(options_json)


# --- 6. Render the graph in Streamlit ---
html_file = "attack_graph_viz.html"

try:
    net.save_graph(html_file)

    HtmlFile = open(html_file, 'r', encoding='utf-8')
    source_code = HtmlFile.read()
    HtmlFile.close()

    components.html(source_code, height=770, scrolling=False)

except Exception as e:
    st.error(f"Error rendering the Pyvis graph: {e}")

# --- 7. Display raw data ---
st.subheader("3. Raw Graph Data (JSON)")
with st.expander("View attack_graph.json contents"):
    st.json(graph_data)
